### ISSUE TITLE
KeyboardState.hidden Returned for Split and Floating Keyboards on iPad.

### ISSUE THREAD

**Issue by alpaca211** [vursin/keyboard_detection#1]
When using split or floating keyboards on iPad, `KeyboardState` always returns `KeyboardState.hidden`, regardless of the actual visibility of the keyboard.

**Comment by lamnhan066** [comment]
Hi @alpaca211 

I'm using the bottom view insets to detect the keyboard, so I think currently there is no way to detect the floating keyboard by using the bottom view insets.
