### ISSUE TITLE
Once I call setState() from onChanged(), it runs forever

### ISSUE THREAD

**Issue by saif-ellafi** [vursin/keyboard_detection#3]
Hello there,

Thanks for the plugin.

For some reason, whenever my onChanged() call is made due to Keyboard showing up, if I call setState() within (after some condition), the onChange() keeps getting called every frame forever, even if I am not touching anything on the screen. The loop goes on forever thinking the state has changed when it has not.

Could there be anything wrong with the plugin or my app for some reason? Not doing anything weird on my end.

Best regards

**Comment by saif-ellafi** [comment]
I worked this around by storing last changed state and it is fine now. My best guess is that high frame rates kept thousands of setState() calls in a queue.

**Comment by lamnhan066** [comment]
Hi @saif-ellafi

I reopen this issue because this is a real issue of the package that I just release an update to fix it. Could you try it and let me know the result?

**Comment by lamnhan066** [comment]
Feel free to reopen this issue if you still have it as I have fixed it. Thank you.

**Comment by saif-ellafi** [comment]
Ohh I am super glad this was a valid report. Will test after Tuesday. @lamnhan066
